#!/usr/bin/bash

cd $(dirname $0)

interval=${1:-43200} # seconds

###

f=config/mirrormanager2.cfg

sed -i "s/{UMDL_PREFIX}//"  $f
sed -i "s|{DB_URL}|$DB_URL|"  $f
sed -i "s/{SECRET_KEY}//"  $f
sed -i "s/{PASSWORD_SEED}//"  $f
sed -i "s/{EXCLUDES}//"  $f

mm_log_dir=$(pwd)/logs
mkdir -p $mm_log_dir/crawler
sed -i "s|{MM_LOG_DIR}|$mm_log_dir|"  $f

###

log() {
    echo "$(date), $1"
}

set +e

while true
do
    log "start mm2_crawler"

    # adjust the threads num by env
    threads=${THREADS:-5}

    > ./crawler_logs

    SECONDS=0

    # avoid the python threads to be blocked by timeout
    timeout -k 10 ${interval}s ./mm2_crawler -c config/mirrormanager2.cfg --include-private -t $threads --disable-fedmsg --repodata > ./crawler_logs 2>&1

    seconds=$SECONDS
    log "mm2_crawler done after $seconds seconds"

    if [ $seconds -lt $interval ]; then
        sleep $(($interval - $seconds))
    fi
done
