#!/usr/bin/bash

cd $(dirname $0)

interval=${1:-1500} # seconds

###

f=config/mirrormanager2.cfg

prefix=$UMDL_PREFIX
if [ "$(basename $prefix)" != "openeuler" ]; then
    echo "invalid UMDL_PREFIX: $UMDL_PREFIX"
    exit 1
fi
prefix=$(dirname $prefix)

sed -i "s|{UMDL_PREFIX}|$prefix|"  $f
sed -i "s|{DB_URL}|$DB_URL|"  $f
sed -i "s/{SECRET_KEY}//"  $f
sed -i "s/{PASSWORD_SEED}//"  $f
sed -i "s/{EXCLUDES}//"  $f

mm_log_dir=$(pwd)/logs
mkdir -p $mm_log_dir/crawler
sed -i "s|{MM_LOG_DIR}|$mm_log_dir|"  $f

###

log() {
    echo "$(date), $1"
}

set +e

while true
do
    log "start mm2_update-master-directory-list"

    SECONDS=0

    timeout -k 10 ${interval}s ./mm2_update-master-directory-list -c ./config/mirrormanager2.cfg --logfile log > /dev/null 2>&1

    seconds=$SECONDS
    log "mm2_update-master-directory-list done after $seconds seconds"

    if [ $seconds -lt $interval ]; then
        sleep $(($interval - $seconds))
    fi
done
